server:
  port: 8001

# 引入microcloud-security安全配置模块,可以删除此配置
#security:
#  sessions: stateless
#  basic:
#    enabled: true
#  user:
#    name: mldnjava
#    password: hello
#    role:
#    - USER

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.niu.vo
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: root123
#    filters: stat,wall,log4j
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200